// Generated by https://quicktype.io

export interface IP {
  ip: string
}

export interface IPAddress {
  ip:       string;
  hostname: string;
  city:     string;
  region:   string;
  country:  string;
  loc:      string;
  org:      string;
  postal:   string;
  timezone: string;
}
